/**
 * Copies the ngano catalogue data files into this package and regenerates the
 * embedded snapshot module used by `new Catalogue()`.
 *
 * Source of truth is `<repo>/data/*.json`, which this package never edits.
 * Run `npm run sync-data` after the catalogue changes. `npm run build` runs it
 * automatically through the `prebuild` script.
 *
 * Outputs:
 *   data/<name>.json        verbatim copies, shipped so consumers can read the
 *                           raw catalogue via the `ngano/data/*.json` subpath
 *   src/data/snapshot.ts    generated module embedding the same bytes, so that
 *                           `new Catalogue()` works offline in any runtime,
 *                           including browsers with no filesystem
 */
import { mkdirSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

const here = dirname(fileURLToPath(import.meta.url));
const pkgRoot = resolve(here, "..");
const repoRoot = resolve(pkgRoot, "..", "..");
const sourceDir = join(repoRoot, "data");

/** The five files the SDK needs. Everything else in `data/` belongs to the site. */
const FILES = [
  "catalogue.json",
  "countries.json",
  "languages.json",
  "language_codes.json",
  "field_map.json",
];

const dataDir = join(pkgRoot, "data");
const genDir = join(pkgRoot, "src", "data");
mkdirSync(dataDir, { recursive: true });
mkdirSync(genDir, { recursive: true });

/**
 * Embeds a JSON document as a `JSON.parse` call over a string literal. This
 * parses faster than an inline object literal and keeps the bundle smaller.
 *
 * @param {unknown} value parsed JSON document
 * @returns {string} JavaScript source for the value
 */
function embed(value) {
  return `JSON.parse(${JSON.stringify(JSON.stringify(value))})`;
}

const parsed = {};
for (const file of FILES) {
  const raw = readFileSync(join(sourceDir, file), "utf8");
  const value = JSON.parse(raw);
  parsed[file] = value;
  // Re-serialise compactly. The copy stays byte-equivalent as a document.
  writeFileSync(join(dataDir, file), `${JSON.stringify(value)}\n`);
}

const generated = `// Generated by scripts/sync-data.mjs. Do not edit by hand.
// Source: <repo>/data/{${FILES.map((f) => f.replace(".json", "")).join(",")}}.json
// Catalogue data is licensed CC-BY-4.0.
import type { FieldMap, Language, LanguageCodes, RawCountry, RawDataset } from "../types.js";

/** Dataset records bundled with the package, used by \`new Catalogue()\`. */
export const CATALOGUE = ${embed(parsed["catalogue.json"])} as RawDataset[];

/** Country reference data bundled with the package. */
export const COUNTRIES = ${embed(parsed["countries.json"])} as RawCountry[];

/** Language reference data bundled with the package, one entry per BCP 47 tag. */
export const LANGUAGES = ${embed(parsed["languages.json"])} as Language[];

/** The ISO 639-3 registry every language value in the SDK resolves through. */
export const LANGUAGE_CODES = ${embed(parsed["language_codes.json"])} as LanguageCodes;

/** Column mapping rules bundled with the package. */
export const FIELD_MAP = ${embed(parsed["field_map.json"])} as FieldMap;

/** Number of dataset records in the bundled snapshot. */
export const SNAPSHOT_SIZE = CATALOGUE.length;
`;

writeFileSync(join(genDir, "snapshot.ts"), generated);

const counts = FILES.map((f) => {
  const v = parsed[f];
  return `${f} (${Array.isArray(v) ? `${v.length} records` : "object"})`;
}).join(", ");
process.stdout.write(`ngano: synced ${counts}\n`);
