//! Build script: stages the ngano JSON data files into `OUT_DIR` so that the
//! library can `include_str!` them.
//!
//! The canonical copies live in the repository at `../../data/`. They are not
//! inside the crate directory, so a published crate cannot reference them.
//! This script therefore keeps a vendored snapshot in `data/` next to the
//! manifest: when the repository copies are present it refreshes the snapshot,
//! and in every case it copies the snapshot into `OUT_DIR`.

use std::fmt::Write as _;
use std::fs;
use std::path::{Path, PathBuf};

const FILES: [&str; 5] = [
    "catalogue.json",
    "countries.json",
    "languages.json",
    "language_codes.json",
    "field_map.json",
];

fn main() {
    let manifest = PathBuf::from(std::env::var("CARGO_MANIFEST_DIR").expect("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("OUT_DIR"));
    let vendored = manifest.join("data");
    let upstream = manifest.join("../../data");

    fs::create_dir_all(&vendored).expect("create vendored data directory");

    for name in FILES {
        let upstream_file = upstream.join(name);
        let vendored_file = vendored.join(name);

        if upstream_file.is_file() {
            println!("cargo:rerun-if-changed={}", upstream_file.display());
            refresh(&upstream_file, &vendored_file);
        }

        assert!(
            vendored_file.is_file(),
            "missing data file {}: the crate needs either ../../data/{name} or data/{name}",
            vendored_file.display()
        );
        println!("cargo:rerun-if-changed={}", vendored_file.display());
        fs::copy(&vendored_file, out.join(name))
            .unwrap_or_else(|e| panic!("copy {name} into OUT_DIR: {e}"));
    }

    generate_snippet_check(&manifest, &out);

    println!("cargo:rerun-if-changed=build.rs");
}

/// Placeholder tokens in `snippets.json`, and the real values used to compile
/// them. The published snippets keep the tokens; only this check substitutes.
const SNIPPET_VALUES: [(&str, &str); 7] = [
    ("{{LANGUAGE}}", "sna"),
    ("{{COUNTRY_ISO2}}", "ZW"),
    ("{{COUNTRY_NAME}}", "Zimbabwe"),
    ("{{DATASET_ID}}", "waxal-corpus-paper"),
    ("{{HF_REPO}}", "google/fleurs"),
    ("{{CONFIG}}", "sn_zw"),
    ("{{TASK}}", "ASR"),
];

/// Turn the Rust snippets in `snippets.json` into a module per snippet, with
/// the placeholders filled in, so that the test suite compiles them for real.
///
/// A published crate without `snippets.json` simply gets an empty file.
fn generate_snippet_check(manifest: &Path, out: &Path) {
    let source = manifest.join("snippets.json");
    println!("cargo:rerun-if-changed={}", source.display());

    let mut generated = String::from("// Generated by build.rs from snippets.json. Do not edit.\n");
    if let Ok(raw) = fs::read_to_string(&source) {
        let doc: serde_json::Value =
            serde_json::from_str(&raw).expect("snippets.json is not valid json");
        let snippets = doc
            .get("snippets")
            .and_then(serde_json::Value::as_object)
            .expect("snippets.json needs a snippets object");
        for (name, body) in snippets {
            // The cli snippet is a shell transcript, not Rust.
            if name == "cli" {
                continue;
            }
            let body = body
                .as_str()
                .unwrap_or_else(|| panic!("snippet {name} is not a string"));
            let mut filled = body.to_string();
            for (token, value) in SNIPPET_VALUES {
                filled = filled.replace(token, value);
            }
            let module: String = name
                .chars()
                .map(|c| if c.is_ascii_alphanumeric() { c } else { '_' })
                .collect();
            writeln!(
                generated,
                "pub mod snippet_{module} {{\n#![allow(dead_code, unused_imports, clippy::all)]\n{filled}\n}}"
            )
            .expect("write generated snippet module");
        }
    }
    fs::write(out.join("snippets_compiled.rs"), generated)
        .expect("write snippets_compiled.rs into OUT_DIR");
}

/// Copy `src` over `dst` only when the contents differ, so untouched builds do
/// not churn file timestamps.
fn refresh(src: &Path, dst: &Path) {
    let new = fs::read(src).unwrap_or_else(|e| panic!("read {}: {e}", src.display()));
    let current = fs::read(dst).ok();
    if current.as_deref() != Some(new.as_slice()) {
        fs::write(dst, &new).unwrap_or_else(|e| panic!("write {}: {e}", dst.display()));
    }
}
