#!/usr/bin/env python3
"""Merge each SDK's self-verified snippets.json into data/snippets.json.

Each package owns its own snippets and tests that they compile, so the website and
the MCP server never serve invented code. Run after changing any SDK's public API.
"""
from __future__ import annotations
import json, sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SOURCES = {
    "python": ROOT / "packages/python/snippets.json",
    "javascript": ROOT / "packages/js/snippets.json",
    "rust": ROOT / "packages/rust/snippets.json",
}
REQUIRED = ["catalogue_filter", "stream_filter", "single_dataset",
            "language_page", "country_page", "dataset_page", "cli"]
TOKENS = {"{{LANGUAGE}}", "{{COUNTRY_ISO2}}", "{{COUNTRY_NAME}}", "{{DATASET_ID}}",
          "{{HF_REPO}}", "{{CONFIG}}", "{{TASK}}"}

def main() -> int:
    out: dict[str, object] = {
        "$comment": "Generated by scripts/merge_snippets.py. Each SDK owns and tests its own "
                    "snippets; this file is the merged copy the website and MCP server serve. "
                    "Do not edit by hand.",
        "version": 1,
        "placeholders": sorted(TOKENS),
        "languages": {},
    }
    errors: list[str] = []
    for lang, path in SOURCES.items():
        if not path.exists():
            errors.append(f"missing {path.relative_to(ROOT)}")
            continue
        doc = json.loads(path.read_text(encoding="utf-8"))
        snips = doc.get("snippets") or {}
        for key in REQUIRED:
            if key not in snips:
                errors.append(f"{lang}: missing snippet '{key}'")
        for key, body in snips.items():
            import re
            for tok in re.findall(r"\{\{[A-Z_]+\}\}", body):
                if tok not in TOKENS:
                    errors.append(f"{lang}.{key}: unknown placeholder {tok}")
        out["languages"][lang] = {
            "language": doc.get("language", lang),
            "install": doc.get("install"),
            "install_audio": doc.get("install_audio"),
            "package": doc.get("package", "ngano"),
            "shell_snippets": doc.get("shell_snippets", ["cli"]),
            "snippets": snips,
        }
    if errors:
        for e in errors:
            print(f"error: {e}", file=sys.stderr)
        return 1
    dest = ROOT / "data/snippets.json"
    dest.write_text(json.dumps(out, ensure_ascii=False, indent=1) + "\n", encoding="utf-8")
    total = sum(len(v["snippets"]) for v in out["languages"].values())
    print(f"wrote {dest.relative_to(ROOT)}: {len(out['languages'])} languages, {total} snippets")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
