#!/usr/bin/env python3
"""Regenerate the credits section of README.md from data/credits.json.

The section lives between two HTML comment markers in README.md:

    <!-- credits:start -->
    ... generated ...
    <!-- credits:end -->

Nothing between those markers should be edited by hand. Change
data/credits.json and run this script instead:

    python scripts/render_readme_credits.py
    python scripts/render_readme_credits.py --check   # CI: fail if stale

Placeholder handles in credits.json are rendered as they are, so an
unfinished link is visible rather than silently dropped.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path
import json

ROOT = Path(__file__).resolve().parent.parent
README = ROOT / "README.md"
CREDITS = ROOT / "data" / "credits.json"

START = "<!-- credits:start -->"
END = "<!-- credits:end -->"
WARNING = "<!-- Generated by scripts/render_readme_credits.py from data/credits.json. Do not edit by hand. -->"


def render(credits: dict) -> str:
    author = credits["author"]
    project = credits["project"]
    lines: list[str] = [START, WARNING, ""]

    lines.append(f"**{author['name']}**" + (f" ({author['short_name']})" if author.get("short_name") else ""))
    if author.get("tagline"):
        lines.append("")
        lines.append(f"_{author['tagline']}_")
    if author.get("bio"):
        lines.append("")
        lines.append(author["bio"])
    if author.get("email"):
        lines.append("")
        lines.append(f"Contact: <{author['email']}>")

    links = credits.get("links", [])
    if links:
        lines.append("")
        lines.append("| Where | Handle |")
        lines.append("| --- | --- |")
        for link in links:
            handle = link.get("handle") or link["label"]
            lines.append(f"| {link['label']} | [{handle}]({link['url']}) |")

    meaning = project.get("meaning")
    if meaning:
        lines.append("")
        lines.append(f"**{project['name']}** is {meaning}")

    acknowledgements = credits.get("acknowledgements", [])
    if acknowledgements:
        lines.append("")
        lines.append("### Acknowledgements")
        lines.append("")
        for item in acknowledgements:
            lines.append(f"- {item}")

    citation = project.get("citation", {})
    if citation:
        lines.append("")
        lines.append("### Citation")
        lines.append("")
        lines.append("```bibtex")
        lines.append(f"@software{{ngano{citation.get('year', '')},")
        lines.append(f"  title   = {{{citation.get('title', project['name'])}}},")
        lines.append(f"  author  = {{{author['name']}}},")
        lines.append(f"  year    = {{{citation.get('year', '')}}},")
        lines.append(f"  url     = {{{project.get('repo', project.get('domain', ''))}}},")
        lines.append(f"  license = {{{project.get('code_licence', 'MIT')}}}")
        lines.append("}")
        lines.append("```")

    lines.append("")
    lines.append(END)
    return "\n".join(lines)


def splice(readme_text: str, block: str) -> str:
    start = readme_text.find(START)
    end = readme_text.find(END)
    if start == -1 or end == -1:
        raise SystemExit(f"error: README.md is missing the {START} / {END} markers")
    if end < start:
        raise SystemExit("error: README.md credits markers are in the wrong order")
    return readme_text[:start] + block + readme_text[end + len(END):]


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true",
                        help="exit non-zero if README.md is out of date, write nothing")
    args = parser.parse_args()

    credits = json.loads(CREDITS.read_text(encoding="utf-8"))
    current = README.read_text(encoding="utf-8")
    updated = splice(current, render(credits))

    if args.check:
        if current != updated:
            print("README.md credits section is stale, run scripts/render_readme_credits.py",
                  file=sys.stderr)
            return 1
        print("README.md credits section is up to date")
        return 0

    if current == updated:
        print("README.md credits section already up to date")
        return 0
    README.write_text(updated, encoding="utf-8")
    print("README.md credits section regenerated from data/credits.json")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
